name: Building CapibaraZero docs

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  deploy:
    name: Test docs building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Build website
        run: npm run build